[google_service_account]
type = "service_account"
project_id = "vaulted-bazaar-462700-h6"
private_key_id = "2647b985eab6377df85bec90f591b8a98fcb7856"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDV4FSEklYqJ3vv
nI5vLs7Dpu5aXJHkHb314XSxy5wjXA5t5dbmuX+hnrjxEYiTH+O9xgp2iAxWjfBl
CjHcX1LPin5j1yXIcgX3kl8be9WQFJFLu2zDkbj0uNNOpaDoRJ2xUw/qyPNlD1ZP
E/lCKFe8QBiXFllq99MbGLtwKcWZXjQpu7yDLHlmvciNSKoOmp1a9MBwLl/HQIAz
eAV/iI2SDCzMhK6duLDGoiVOpPvC+5kpbVJXSGEV0D90Drq7F3MwhtnvYVt3emlp
2nx17O/RCjowFHGsuSu1QtYJc1wLiyNJw/kdyMhjRakfsQ4ub+KorlrD8GiJzXgI
f2lLM10JAgMBAAECggEACqWgv3rDdFTD3DFIe+tyGpZQTkpGbvs2Div7kbBHpRD7
nOfws0qvul166nFLgbt4LGXT9oOeTZ7CRV1lDwnlxvQnh5PZyyk199WfC3C2OHZ1
pzX8252A/hnHVyZypK1pxj6Sz8bSKwlA7C3b3jnA6FuufbL8n5EXvsUT66kAr7pD
9BRPn2ivF73ZoYBXuX/k5dNQ3TrvAeFSt96oKFnHHm1ru5SzJWVzZMDB3UbChWVg
ZlHBsu4/geyv0xKDXYgyfLzSXTG1RkCgVhsRkqSVRUangVhQFQN8AwTyivNPuRP0
kwmrNRoYhg87BGNE+mDWyy6cMS+5aAo0WI0Ze7WbQQKBgQD8i5TzTNacbqfNi2JT
OM8gLUR3mqKR6xAV/WtNhSw+Qk9z+LfOZRm42KRSfChXrD+yE2/mo/msTaQeqBYG
vx+L7J46syGlOJN0In0mnzf2ZCzxWdxe7zOBRh20P1vjh4U3Ma8tcfdoKujQnf94
EyGPCWcaIIAfoWUEDzUIf7O3WQKBgQDYzVQz6SN8p/mf4RAvEIS4KzM7VYrYCUgu
y9CIMNJx5kYbG5BmHkmcxhQ3fkgVbDt3r53spZ55IhSvoFs5TAAP/rcj7CrNg6/J
3jnGimKXHdqEHnZr2ozD23j4Na6V3wgHZrnLGcQk7QOVQDCsxaxRMCMCqkWXWsP+
hve/y3PNMQKBgHfJCQxh3MV0Ivl2bFvG7U94ySnl2chWc1nKytOJIBQjxaXfSeeG
wq2PbFmHdGcpV0jyuTfvfORCK18zIMdwbdkjkWWMQ6AndqE2HqBsEtI2b67GjaUl
1gsyI7Kz/rSsOf6U/V8T2GK7P5R77ImaoWdD8XhOBBd8qPpE8EWotKh5AoGBALch
4nGjCq3euhaaJ3CKFIH5Q+Jn5MuOM6IL2g9gpjM+H5QAWZ5ZETdTfnpNupgV/7me
59ihIdcSucSMwOIKV7crIwo+EP3esdvkUotqE9OwjQezL7b1OpiqyGlp9xpz9jVC
ScjM8Al9B9zIBxW6OE+wSLKUoAo0yoAzBA3Hzv7RAoGAaoIb3q2xDBgToSKODdA6
w4FxrpxrY/ltRGYpElvnTd31WxwASaUyGqPxRJwUv5JQjK/Wpiu51+2ggxRW3+gQ
Eow4LHC9WD82nBoaF/w2VDtfrtNxAWiUln0Q+Q0dbuuGni1AJ19E6a9eLJZ79W69
Fgx6gstkkt5CTI1kHUfAoPw=
-----END PRIVATE KEY-----
"""
client_email = "streamlit-sheets@vaulted-bazaar-462700-h6.iam.gserviceaccount.com"
client_id = "105640482875357029733"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets%40vaulted-bazaar-462700-h6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
